---
title: Vervang eenvoudige regex-patronen met Python
hero_image: images/banner.png
description: Vervang tekstpatronen met Python en regex
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "regex, python"
site_areas:
steps:
  - title: Patronen vervangen

