---
title: Substitute simple regex patterns with Python
hero_image: images/banner.png
description: Replace character patterns with Python and regex
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "regex, python"
site_areas:
steps:
  - 
    title: Replacing patterns

