---
title: Sustituye patrones simples de expresiones regulares con Python
hero_image: images/banner.png
description: Reemplaza patrones de caracteres con Python y regex
original_url:
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum:
interests:
technologies: "regex, python"
site_areas:
steps:
  - 
    title: Reemplazando patrones

